---
# Set up access point.

- hosts: edison
  remote_user: dwatson
  become: yes
  vars_files:
    - private.yaml

  tasks:
    - name: Install dnsmasq.
      package:
        name: dnsmasq
        state: present

    - name: Install hostapd.
      package:
        name: hostapd
        state: present

    - name: Copy dhcpcd.conf.
      copy:
        src: dhcpcd.conf
        dest: /etc/dhcpcd.conf
        owner: root
        group: root
        mode: 0664
      notify:
        - restart dhcpcd

    - name: Copy dnsmasq.conf.
      copy:
        src: dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0664
      notify:
        - restart dnsmasq

    - name: Copy hostapd.conf.
      template:
        src: hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: 0664
      notify:
        - restart hostapd

    - name: Copy default hostapd.
      template:
        src: default_hostapd
        dest: /etc/default/hostapd
        owner: root
        group: root
        mode: 0664
      notify:
        - restart hostapd

    - name: Enable dhcpcd
      service:
        name: dhcpcd
        enabled: yes

    - name: Enable dnsmasq
      service:
        name: dnsmasq
        enabled: yes

    - name: Enable hostapd
      service:
        name: hostapd
        masked: no
        enabled: yes

  handlers:
    - name: restart dhcpcd
      service:
        name: dhcpcd
        state: restarted

    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

    - name: restart hostapd
      service:
        name: hostapd
        state: restarted
