---
# Set up the actual simulator app.

- hosts: rpi
  remote_user: dwatson
  become: yes

  tasks:
    - name: Create home directories.
      file:
        path: /home/dwatson/{{ item.dir }}
        owner: dwatson
        group: dwatson
        state: directory
        mode: '0755'
      with_items:
        - { dir: 'work' }
        - { dir: 'work/ftc_simulator' }
        - { dir: 'work/ftc_simulator/src' }

    - name: Create www-data directories.
      file:
        path: /var/www/{{ item.dir }}
        owner: www-data
        group: www-data
        state: directory
        mode: '0755'
      with_items:
        - { dir: 'work/ftc_simulator/data' }
        - { dir: 'work/ftc_simulator/data/programs' }
        - { dir: 'work/ftc_simulator/data/samples' }

    - name: Copy requirements file.
      copy:
        src: /Users/dwatson/work/ftc_simulator/src/requirements.txt
        dest: /home/dwatson/work/ftc_simulator/src/requirements.txt
        owner: dwatson
        group: dwatson
        mode: 0644

    - name: Create venv for insteon programs.
      pip:
        requirements: /home/dwatson/work/ftc_simulator/src/requirements.txt
        virtualenv: /home/dwatson/work/ftc_simulator/src/venv
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Copy src files.
      copy:
        src: /Users/dwatson/work/ftc_simulator/src/{{ item.src }}
        dest: /home/dwatson/work/ftc_simulator/src/
        owner: dwatson
        group: dwatson
        mode: 0644
      with_items:
        - { src: 'server.py' }
        - { src: 'fetch_from_phone.py' }
        - { src: 'setup.sql' }

    - name: Copy samples.
      copy:
        src: "{{ item }}"
        dest: /var/www/work/ftc_simulator/data/samples/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "/Users/dwatson/work/ftc_simulator/data/samples/*.blk"

    - name: Copy static html files.
      local_action: command rsync -av /Users/dwatson/work/ftc_simulator/static {{ inventory_hostname }}:~/
      become: no

    - name: Move static files into the correct directory.
      command: rsync -av /home/dwatson/static/ /var/www/html

    - name: Fix html file permissions.
      file:
        path: /var/www
        owner: www-data
        group: www-data
        recurse: yes
        state: directory

    - name: Copy ftc sim uwsgi config.
      copy:
        src: ftc_sim_uwsgi.ini
        dest: /etc/uwsgi/apps-available/
        owner: root
        group: root
        mode: 0644
      notify:
        - restart uwsgi

    - name: Enable ftc sim uwsgi config.
      file:
        src: /etc/uwsgi/apps-available/ftc_sim_uwsgi.ini
        dest: /etc/uwsgi/apps-enabled/ftc_sim_uwsgi.ini
        state: link
      notify:
        - restart uwsgi

  handlers:
    - name: restart uwsgi
      service:
        name: uwsgi
        enabled: yes
        state: restarted
