---
# Set up infrastructure.

- hosts: edison
  remote_user: dwatson
  become: yes

  tasks:
    - name: Set timezone.
      timezone:
        name: America/Detroit

    - name: Install nginx.
      package:
        name: nginx-light
        state: present

    - name: Install uwsgi.
      package:
        name: uwsgi
        state: present

    - name: Install uwsgi python plugin.
      package:
        name: uwsgi-plugin-python3
        state: present

    - name: Install python venv.
      package:
        name: python3-venv
        state: present

    - name: Disable default nginx config.
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx

    - name: Copy nginx_ftc_sim.conf.
      copy:
        src: nginx_ftc_sim.conf
        dest: /etc/nginx/sites-available/nginx_ftc_sim.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx

    - name: Enable nginx_ftc_sim.conf.
      file:
        src: /etc/nginx/sites-available/nginx_ftc_sim.conf
        dest: /etc/nginx/sites-enabled/nginx_ftc_sim.conf
        state: link
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
