---
# Initial setup.

- hosts: edison
  remote_user: pi
  become: True
  vars_files:
    - private.yaml

  tasks:
    - name: Create a user group.
      group: name=dwatson

    - name: Create normal user.
      user: name=dwatson
            comment="David Watson"
            group=dwatson
            groups="sudo"
            password="{{ password }}"

    - name: Copy ssh key to new user.
      authorized_key:
        user: dwatson
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
